apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: cluster-in-existing-vpc
  region: ap-south-1

vpc:
  subnets:
    private:
      ap-south-1a: { id: subnet-07395fe366bca95ea }
      ap-south-1b: { id: subnet-0a76334c209955d03 }

nodeGroups:
  - name: ng-1-workers
    labels: { role: workers }
    instanceType: t3.medium
    desiredCapacity: 2
    privateNetworking: true
    ssh:
      allow: true
      publicKeyName: K8s
