version: '3.8'

services:
  backend:
    build:
      context: ./backend-app
    ports:
      - "8080:8080"
    environment:
      - AWS_REGION=ap-south-1
      - TABLE_NAME=my-table

  frontend:
    build:
      context: ./frontend-app
    ports:
      - "3000:3000"
    depends_on:
      - backend

